version: '3.9'

services:
    web:
        build:
            context: ./
            dockerfile: ./docker/dev/Dockerfile
        image: laravel-api
        container_name: laravel-api
        working_dir: /var/www
        volumes:
            - ./:/var/www
        env_file:
            - .env
        ports:
            - 8080:80
        restart: unless-stopped